######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 12 20:08:46 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qtstickies.cxx
