######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 12 23:14:24 2015
######################################################################

QT += sql widgets
TEMPLATE = app
TARGET = qtstickies.app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += HeaderLabel.h StickyWindow.h
SOURCES += HeaderLabel.cxx qtstickies.cxx StickyWindow.cxx
RESOURCES = qtstickies.qrc
